spring:
  datasource:
    url: jdbc:mysql://192.168.219.104:3306/dashboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dashboard_user
    password: jhj!236884400
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성 (운영 환경에서는 none 또는 validate 추천)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
